def xml = new XmlParser().parse("https://stackexchange.com/feeds/tagsets/109910/groovy-questions?sort=noanswers")
println("Names")
println(xml.entry.author.name*.text().join(","))
println()
println("Titles")
println(xml."**".title*.text().join('\n'))
println()
println("tags")
println(xml."**".@term.grep { it?.size() > 2 } )
println()
